// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

RWStructuredBuffer<float3> Result;

StructuredBuffer<float3> Input;

const float PI=3.14159;

[numthreads(4,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    
    Result[id.x*6]=Input[id.x*3];
    Result[id.x*6+1]=Input[id.x*3+1];
    Result[id.x*6+2]=Input[id.x*3+2];

    Result[id.x*6+3]=Input[id.x*3];
    Result[id.x*6+4]=Input[id.x*3+2];
    Result[id.x*6+5]=Input[id.x*3+3];
}
